<h1><center>Geocoding Api's</center></h1>

## Google API

* [**Google_Free_Tier**](https://cloud.google.com/free/?utm_source=google&utm_medium=cpc&utm_campaign=latam-LATAM-all-es-dr-AKWS-all-all-trial-p-dr-1011454-LUAC0013610&utm_content=text-ad-none-any-DEV_c-CRE_540885993580-ADGP_Hybrid%20%7C%20BKWS%20-%20PHR%20%7C%20Txt%20~%20Management-Tools_Console-KWID_43700065922071537-kwd-651816590614&utm_term=KW_google%20console-ST_Google%20Console&gclid=Cj0KCQjwnbmaBhD-ARIsAGTPcfWVMlJlTFywFNaAo8P-MNL4_gM6L7yucqAQ37xg1AIEHzpAzF_kkAoaAsszEALw_wcB&gclsrc=aw.ds)
* [**Google_Api_Pricing**](https://mapsplatform.google.com/pricing/)

## HERE Platform

* [**Here_Register**](https://platform.here.com/sign-up?step=verify-identity&aid=www.here.com-start-building)
* [**Here_Princing**](https://www.here.com/pricing)
* [**Geocoding_Documentation**](https://developer.here.com/documentation/geocoding-search-api/dev_guide/topics/endpoint-geocode-brief.html)

In [13]:
import requests
import random
import pandas as pd 
from tqdm import tqdm
from bs4  import BeautifulSoup
from _config import APIKEY_HERE_PLATFORM, TITLE_APP_HERE_PLATFORM
import json 
from tqdm import tqdm
import time
import datetime

import ast

In [8]:
df = pd.read_csv('Precios_Combustibles_Enero.csv')

In [10]:
'''
agente = Nombre_comercial
estado (A) = estado (1)
'''

df.head(2)

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro
0,63,QUINDIO,63001,ARMENIA,ESTACION DE SERVICIO AUTOMOTRIZ TERPEL CENTENARIO,TERPEL,CARRERA 18 # 45 - 55,BIODIESEL EXTRA,8190,1,01/02/2015 12:00:00 AM
1,63,QUINDIO,63001,ARMENIA,ESTACION DE SERVICIO AUTOMOTRIZ TERPEL CENTENARIO,TERPEL,CARRERA 18 # 45 - 55,GASOLINA CORRIENTE OXIGENADA,8140,1,01/02/2015 12:00:00 AM

# Clean Data

In [34]:
## Testing dates convertion

datetime.date.today().year

d = '01/02/2015 12:00:00 AM'

dt = datetime.datetime.strptime(d, '%m/%d/%Y %H:%M:%S %p')
dt.year

2015

In [45]:
df['FechaRegistroDate'] = pd.to_datetime(df['fecharegistro'], format='%m/%d/%Y %H:%M:%S %p')
df[df['FechaRegistroDate'].dt.year == 2018]

# https://sparkbyexamples.com/pandas/pandas-extract-year-from-datetime/

# ['Mes'].max()

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
555,41,HUILA,41770,SUAZA,ESTACION BUENOS AIRES,TERPEL,VEREDA LIBANO CRUCE ACEVEDO - FLORENCIA,BIODIESEL EXTRA,8136,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
556,81,ARAUCA,81794,TAME,ESTACIÓN DE SERVICIO NUEVO SANTANDER,TERPEL,KILOMETRO 21 MAS 850 METROS VÍA TAME,GASOLINA CORRIENTE OXIGENADA,7100,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
557,81,ARAUCA,81794,TAME,ESTACIÓN DE SERVICIO NUEVO SANTANDER,TERPEL,KILOMETRO 21 MAS 850 METROS VÍA TAME,BIODIESEL EXTRA,6750,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
558,41,HUILA,41770,SUAZA,ESTACION BUENOS AIRES,TERPEL,VEREDA LIBANO CRUCE ACEVEDO - FLORENCIA,GASOLINA CORRIENTE OXIGENADA,8730,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
559,18,CAQUETA,18150,CARTAGENA DEL CHAIRA,GASOLINERA EL CHAIRA,TERPEL,CARRERA 4 No. 11-04 BARRIO GAITAN,BIODIESEL EXTRA,8860,1,01/03/2018 12:00:00 AM,2018-01-03 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13569,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,BIODIESEL EXTRA,7400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13570,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,BIODIESEL EXTRA,8450,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13571,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA EXTRA OXIGENADA,11400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13572,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,GASOLINA CORRIENTE OXIGENADA,7550,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13573,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA CORRIENTE OXIGENADA,8990,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00

In [49]:
# df2 =  df[(df['Periodo']==2022) & (df['Mes']==6)]
df2 = df[(df['FechaRegistroDate'].dt.year == 2018) & (df['FechaRegistroDate'].dt.month == 5)]
df2

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
1203,76,VALLE DEL CAUCA,76520,PALMIRA,ESTACION DE SERVICIO SERVIBERNA,MOBIL,CARRERA 32 # 11-20,GASOLINA CORRIENTE OXIGENADA,8811,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1204,66,RISARALDA,66400,LA VIRGINIA,ESTACION DE SERVICIO LA VIRGINIA,BIOMAX,CARRERA 8 No. 6-64,GASOLINA EXTRA OXIGENADA,11600,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1205,13,BOLIVAR,13442,MARIA LA BAJA,EDS SAN JERONIMO,TERPEL,CORREGIMIENTO SENA MARIA LA BAJA,BIODIESEL EXTRA,7820,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1206,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1207,20,CESAR,20011,AGUACHICA,ESTACION DE SERVICIO LOS COLUMPIOS,TERPEL,KILOMETRO 5 VIA AGUACHICA - BUCARAMANGA,GASOLINA CORRIENTE OXIGENADA,7200,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13569,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,BIODIESEL EXTRA,7400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13570,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,BIODIESEL EXTRA,8450,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13571,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA EXTRA OXIGENADA,11400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13572,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,GASOLINA CORRIENTE OXIGENADA,7550,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13573,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA CORRIENTE OXIGENADA,8990,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00

In [50]:
df3 =  df2[(df2['departamentonombre']=='ANTIOQUIA') | (df2['departamentonombre']=='BOGOTA D.C.')]
df3

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
1206,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1221,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,TERPEL,CARRERA 27 No. 31C-63 SUR,BIODIESEL EXTRA,7986,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1233,5,ANTIOQUIA,5138,CAÑASGORDAS,LAS HELICONIAS,ZEUSS,PARAJE IMANTAGO,GASOLINA CORRIENTE OXIGENADA,9060,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1236,11,BOGOTA D.C.,11001,BOGOTA D.C.,EDS BIOMAX TINTAL,BIOMAX,AVENIDA CALLE 54 SUR No 89A-55,BIOACEM AL 9%,8110,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1243,5,ANTIOQUIA,5315,GUADALUPE,BOMBA LOS PINOS,ZEUSS,CALLE 51 A No 45-03 17,BIODIESEL EXTRA,8810,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13548,5,ANTIOQUIA,5380,LA ESTRELLA,ESTACION DE SERVICIO ESSO LA VARIANTE,MOBIL,CARRERA 48 No. 101 SUR -386,GASOLINA CORRIENTE OXIGENADA,8620,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13554,5,ANTIOQUIA,5854,VALDIVIA,EDS PUERTO RAUDAL,TERPEL,KILOMETRO 22 PUERTO RAUDAL,BIODIESEL EXTRA,8179,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13559,5,ANTIOQUIA,5321,GUATAPE,ESTACIÓN DE SERVICIO ASTILLEROS GUATAPE,TEXACO,KILOMETRO 27 VÍA MARINILLA - GUATAPE,GASOLINA CORRIENTE OXIGENADA,9090,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13563,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION TEXACO No 25,TEXACO,CALLE 11 SUR No. 15-11,BIODIESEL EXTRA,8350,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13568,5,ANTIOQUIA,5615,CANON DE RIO CLARO,AUTOCENTRO JBAM,MOBIL,Carrera 47 Calle 64A-125,BIODIESEL EXTRA,8515,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00

In [52]:
df3['municipionombre'].value_counts().head(10)

municipionombre
BOGOTA D.C.           1278
MEDELLIN               305
BELLO                   59
ITAGUI                  53
CANON DE RIO CLARO      48
ENVIGADO                46
CAUCASIA                28
SABANETA                27
TURBO                   25
COPACABANA              25
Name: count, dtype: int64

In [53]:
df4 = df3[(df3['departamentonombre']=='BOGOTA D.C.') | ((df3['departamentonombre']=='ANTIOQUIA') & ((df3['municipionombre']=='MEDELLIN') | (df3['municipionombre']=='ITAGUI') | (df3['municipionombre']=='BELLO') | (df3['municipionombre']=='SABANETA') | (df3['municipionombre']=='RIONEGRO') | (df3['municipionombre']=='ENVIGADO')))]
df4.reset_index(inplace = True)
df4.drop(columns = 'index',inplace = True)

C:\Users\pc\AppData\Local\Temp\ipykernel_11620\401858228.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop(columns = 'index',inplace = True)

In [54]:
df4.head(2)

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
0,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,TERPEL,CARRERA 27 No. 31C-63 SUR,BIODIESEL EXTRA,7986,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00

In [55]:
df4['departamentonombre'].unique()

array(['BOGOTA D.C.', 'ANTIOQUIA'], dtype=object)

In [56]:
df4['Dir2'] = df4['direccion'].apply(lambda x : x.replace('#','No'))
df4['Full_Address'] = df4.apply(lambda x : x['direccion'] + ', ' + x['municipionombre'].capitalize() + ', Colombia' , axis = 1)

C:\Users\pc\AppData\Local\Temp\ipykernel_11620\2097013594.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Dir2'] = df4['direccion'].apply(lambda x : x.replace('#','No'))
C:\Users\pc\AppData\Local\Temp\ipykernel_11620\2097013594.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Full_Address'] = df4.apply(lambda x : x['direccion'] + ', ' + x['municipionombre'].capitalize() + ', Colombia' , axis = 1)

In [57]:
df4['Full_Address'].nunique()

558

In [58]:
df4['Full_Address'][0]

'CALLE 45 No. 16-30, Bogota d.c., Colombia'

In [60]:
estaciones =  df4[['agente','direccion','Full_Address']].drop_duplicates(subset = 'agente')
estaciones.reset_index(inplace = True)
estaciones.drop(columns = 'index',inplace = True)

In [61]:
estaciones['Full_Address'][0]

'CALLE 45 No. 16-30, Bogota d.c., Colombia'

In [63]:
address = estaciones['Full_Address'][0]
url = f'https://geocode.search.hereapi.com/v1/geocode?q={address}&apiKey={APIKEY_HERE_PLATFORM}'
response = requests.get(url).json()

In [64]:
response

{'items': [{'title': 'Avenida Calle 45 9-16, 110231 Bogotá, D.C., Colombia',
   'id': 'here:af:streetsection:CUj62WNnCkoYmZxg95FwnA:EAIaAjE2',
   'resultType': 'houseNumber',
   'houseNumberType': 'interpolated',
   'address': {'label': 'Avenida Calle 45 9-16, 110231 Bogotá, D.C., Colombia',
    'countryCode': 'COL',
    'countryName': 'Colombia',
    'countyCode': 'DC',
    'county': 'Bogotá, D.C.',
    'city': 'Bogotá, D.C.',
    'district': 'Chapinero',
    'street': 'Avenida Calle 45 9',
    'postalCode': '110231',
    'houseNumber': '16'},
   'position': {'lat': 4.63204, 'lng': -74.06546},
   'access': [{'lat': 4.63191, 'lng': -74.0655}],
   'mapView': {'west': -74.06636,
    'south': 4.63114,
    'east': -74.06456,
    'north': 4.63294},
   'scoring': {'queryScore': 0.9,
    'fieldScore': {'country': 1.0,
     'city': 1.0,
     'streets': [0.85],
     'houseNumber': 1.0}}},
  {'title': 'Calle 16-30, 110321 Bogotá, D.C., Colombia',
   'id': 'here:af:streetsection:bbKO2BHKtDta7HEFzbMp7A:EAIaAjMw',
   'resultType': 'houseNumber',
   'houseNumberType': 'interpolated',
   'address': {'label': 'Calle 16-30, 110321 Bogotá, D.C., Colombia',
    'countryCode': 'COL',
    'countryName': 'Colombia',
    'countyCode': 'DC',
    'county': 'Bogotá, D.C.',
    'city': 'Bogotá, D.C.',
    'district': 'Santa Fé',
    'street': 'Calle 16',
    'postalCode': '110321',
    'houseNumber': '30'},
   'position': {'lat': 4.60228, 'lng': -74.07204},
   'access': [{'lat': 4.60217, 'lng': -74.07211}],
   'mapView': {'west': -74.07294,
    'south': 4.60138,
    'east': -74.07114,
    'north': 4.60318},
   'scoring': {'queryScore': 0.69,
    'fieldScore': {'country': 1.0,
     'city': 1.0,
     'streets': [0.9],
     'houseNumber': 1.0}}}]}

In [67]:
def Get_Coords(address,apikey):
    
    url = f'https://geocode.search.hereapi.com/v1/geocode?q={address}&apiKey={apikey}'
    
    try : 
        
        response = requests.get(url).json()
        CleanAddress = response['items'][0]['title'].upper()
        LAT = response['items'][0]['position']['lat']
        LNG = response['items'][0]['position']['lng']
        
        results = [CleanAddress,LAT,LNG]
        
    except :
        
        results = ['Not Found','NA','NA']
        
    
    return results

In [68]:
Get_Coords(address,APIKEY_HERE_PLATFORM)

['AVENIDA CALLE 45 9-16, 110231 BOGOTÁ, D.C., COLOMBIA', 4.63204, -74.06546]

# Extracción de coordenadas

In [70]:
coordenadas = []
tiempo = [1,2,2.5]

for i in tqdm(range(len(estaciones['Full_Address'])),colour = 'green'):
    
    try :
        
        R = Get_Coords(estaciones['Full_Address'][i],APIKEY_HERE_PLATFORM)
        geo_source = R[1],R[2]
        coordenadas.append(geo_source)
        
    except :
        
        coordenadas.append('Error')
        
    
    time.sleep(random.choices(tiempo)[0])

  1%|▋                                                                                 | 5/557 [00:18<34:57,  3.80s/it]

KeyboardInterrupt:

In [72]:
coordenadas

[(4.63204, -74.06546),
 (4.59549, -74.10256),
 (4.6322, -74.185),
 (4.60867, -74.20333),
 (4.75082, -74.04352),
 (4.65358, -74.13098)]

In [71]:
estaciones['Coords'] = coordenadas

ValueError: Length of values (6) does not match length of index (557)

In [73]:
len(df4)

1768

In [117]:
estaciones.head(2)

,Nombre_comercial,Direccion,Full_Address,Coords
0,ESTACION DE SERVICIOS PREMIUM LA SEBASTIANA,CARRERA 27 No. 36 SUR-199,"CARRERA 27 No. 36 SUR-199, Envigado, Colombia","(6.16364, -75.56929)"
1,ESTACION DE SERVICIO TEXACO ESTRELLA DE ORIENTE,Km 14 Vte Las Palmas,"Km 14 Vte Las Palmas, Envigado, Colombia","(6.16623, -75.54754)"

In [74]:
df_final = pd.merge(df3,estaciones[['Full_Address','Coords']],how = 'inner' , on = 'Full_Address')

KeyError: "['Coords'] not in index"

In [75]:
df_final.head(3)

NameError: name 'df_final' is not defined

In [ ]:
df_final = pd.merge(df3,estaciones[['Full_Address','Coords']],how = 'inner' , on = 'Full_Address')

In [ ]:
df_final.to_csv('DATASET_FINAL.CSV',index = False)