<h1><center>Geocoding Api's</center></h1>

## Google API

* [**Google_Free_Tier**](https://cloud.google.com/free/?utm_source=google&utm_medium=cpc&utm_campaign=latam-LATAM-all-es-dr-AKWS-all-all-trial-p-dr-1011454-LUAC0013610&utm_content=text-ad-none-any-DEV_c-CRE_540885993580-ADGP_Hybrid%20%7C%20BKWS%20-%20PHR%20%7C%20Txt%20~%20Management-Tools_Console-KWID_43700065922071537-kwd-651816590614&utm_term=KW_google%20console-ST_Google%20Console&gclid=Cj0KCQjwnbmaBhD-ARIsAGTPcfWVMlJlTFywFNaAo8P-MNL4_gM6L7yucqAQ37xg1AIEHzpAzF_kkAoaAsszEALw_wcB&gclsrc=aw.ds)
* [**Google_Api_Pricing**](https://mapsplatform.google.com/pricing/)

## HERE Platform

* [**Here_Register**](https://platform.here.com/sign-up?step=verify-identity&aid=www.here.com-start-building)
* [**Here_Princing**](https://www.here.com/pricing)
* [**Geocoding_Documentation**](https://developer.here.com/documentation/geocoding-search-api/dev_guide/topics/endpoint-geocode-brief.html)

In [1]:
import requests
import random
import pandas as pd 
from tqdm import tqdm
from bs4  import BeautifulSoup
from _config import APIKEY_HERE_PLATFORM, TITLE_APP_HERE_PLATFORM
import json 
from tqdm import tqdm
import time
import datetime

import ast

In [2]:
df = pd.read_csv('Precios_Combustibles_Enero.csv')

In [4]:
'''
agente = Nombre_comercial
estado (A) = estado (1)
'''

df.head(2)

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro
0,63,QUINDIO,63001,ARMENIA,ESTACION DE SERVICIO AUTOMOTRIZ TERPEL CENTENARIO,TERPEL,CARRERA 18 # 45 - 55,BIODIESEL EXTRA,8190,1,01/02/2015 12:00:00 AM
1,63,QUINDIO,63001,ARMENIA,ESTACION DE SERVICIO AUTOMOTRIZ TERPEL CENTENARIO,TERPEL,CARRERA 18 # 45 - 55,GASOLINA CORRIENTE OXIGENADA,8140,1,01/02/2015 12:00:00 AM

# Clean Data

In [5]:
## Testing dates convertion

datetime.date.today().year

d = '01/02/2015 12:00:00 AM'

dt = datetime.datetime.strptime(d, '%m/%d/%Y %H:%M:%S %p')
dt.year

2015

In [6]:
df['FechaRegistroDate'] = pd.to_datetime(df['fecharegistro'], format='%m/%d/%Y %H:%M:%S %p')
df[df['FechaRegistroDate'].dt.year == 2018]

# https://sparkbyexamples.com/pandas/pandas-extract-year-from-datetime/

# ['Mes'].max()

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
555,41,HUILA,41770,SUAZA,ESTACION BUENOS AIRES,TERPEL,VEREDA LIBANO CRUCE ACEVEDO - FLORENCIA,BIODIESEL EXTRA,8136,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
556,81,ARAUCA,81794,TAME,ESTACIÓN DE SERVICIO NUEVO SANTANDER,TERPEL,KILOMETRO 21 MAS 850 METROS VÍA TAME,GASOLINA CORRIENTE OXIGENADA,7100,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
557,81,ARAUCA,81794,TAME,ESTACIÓN DE SERVICIO NUEVO SANTANDER,TERPEL,KILOMETRO 21 MAS 850 METROS VÍA TAME,BIODIESEL EXTRA,6750,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
558,41,HUILA,41770,SUAZA,ESTACION BUENOS AIRES,TERPEL,VEREDA LIBANO CRUCE ACEVEDO - FLORENCIA,GASOLINA CORRIENTE OXIGENADA,8730,1,01/02/2018 12:00:00 AM,2018-01-02 12:00:00
559,18,CAQUETA,18150,CARTAGENA DEL CHAIRA,GASOLINERA EL CHAIRA,TERPEL,CARRERA 4 No. 11-04 BARRIO GAITAN,BIODIESEL EXTRA,8860,1,01/03/2018 12:00:00 AM,2018-01-03 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13569,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,BIODIESEL EXTRA,7400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13570,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,BIODIESEL EXTRA,8450,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13571,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA EXTRA OXIGENADA,11400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13572,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,GASOLINA CORRIENTE OXIGENADA,7550,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13573,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA CORRIENTE OXIGENADA,8990,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00

In [7]:
# df2 =  df[(df['Periodo']==2022) & (df['Mes']==6)]
df2 = df[(df['FechaRegistroDate'].dt.year == 2018) & (df['FechaRegistroDate'].dt.month == 5)]
df2

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
1203,76,VALLE DEL CAUCA,76520,PALMIRA,ESTACION DE SERVICIO SERVIBERNA,MOBIL,CARRERA 32 # 11-20,GASOLINA CORRIENTE OXIGENADA,8811,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1204,66,RISARALDA,66400,LA VIRGINIA,ESTACION DE SERVICIO LA VIRGINIA,BIOMAX,CARRERA 8 No. 6-64,GASOLINA EXTRA OXIGENADA,11600,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1205,13,BOLIVAR,13442,MARIA LA BAJA,EDS SAN JERONIMO,TERPEL,CORREGIMIENTO SENA MARIA LA BAJA,BIODIESEL EXTRA,7820,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1206,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1207,20,CESAR,20011,AGUACHICA,ESTACION DE SERVICIO LOS COLUMPIOS,TERPEL,KILOMETRO 5 VIA AGUACHICA - BUCARAMANGA,GASOLINA CORRIENTE OXIGENADA,7200,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13569,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,BIODIESEL EXTRA,7400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13570,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,BIODIESEL EXTRA,8450,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13571,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA EXTRA OXIGENADA,11400,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13572,52,NARIÑO,52835,TUMACO,ESTADERO Y ESTACION DE SERVICIO LAS PALMAS,TERPEL,KILOMETRO 52 VIA TUMACO - PASTO,GASOLINA CORRIENTE OXIGENADA,7550,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00
13573,8,ATLANTICO,8001,BARRANQUILLA,ESTACION DE SERVICIO TERPEL PARAISO,TERPEL,CALLE 76 No. 58-31,GASOLINA CORRIENTE OXIGENADA,8990,1,05/13/2018 12:00:00 AM,2018-05-13 12:00:00

In [8]:
df3 =  df2[(df2['departamentonombre']=='ANTIOQUIA') | (df2['departamentonombre']=='BOGOTA D.C.')]
df3

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
1206,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1221,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,TERPEL,CARRERA 27 No. 31C-63 SUR,BIODIESEL EXTRA,7986,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1233,5,ANTIOQUIA,5138,CAÑASGORDAS,LAS HELICONIAS,ZEUSS,PARAJE IMANTAGO,GASOLINA CORRIENTE OXIGENADA,9060,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1236,11,BOGOTA D.C.,11001,BOGOTA D.C.,EDS BIOMAX TINTAL,BIOMAX,AVENIDA CALLE 54 SUR No 89A-55,BIOACEM AL 9%,8110,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1243,5,ANTIOQUIA,5315,GUADALUPE,BOMBA LOS PINOS,ZEUSS,CALLE 51 A No 45-03 17,BIODIESEL EXTRA,8810,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
13548,5,ANTIOQUIA,5380,LA ESTRELLA,ESTACION DE SERVICIO ESSO LA VARIANTE,MOBIL,CARRERA 48 No. 101 SUR -386,GASOLINA CORRIENTE OXIGENADA,8620,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13554,5,ANTIOQUIA,5854,VALDIVIA,EDS PUERTO RAUDAL,TERPEL,KILOMETRO 22 PUERTO RAUDAL,BIODIESEL EXTRA,8179,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13559,5,ANTIOQUIA,5321,GUATAPE,ESTACIÓN DE SERVICIO ASTILLEROS GUATAPE,TEXACO,KILOMETRO 27 VÍA MARINILLA - GUATAPE,GASOLINA CORRIENTE OXIGENADA,9090,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13563,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION TEXACO No 25,TEXACO,CALLE 11 SUR No. 15-11,BIODIESEL EXTRA,8350,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00
13568,5,ANTIOQUIA,5615,CANON DE RIO CLARO,AUTOCENTRO JBAM,MOBIL,Carrera 47 Calle 64A-125,BIODIESEL EXTRA,8515,1,05/12/2018 12:00:00 AM,2018-05-12 12:00:00

In [9]:
df3['municipionombre'].value_counts().head(10)

municipionombre
BOGOTA D.C.           1278
MEDELLIN               305
BELLO                   59
ITAGUI                  53
CANON DE RIO CLARO      48
ENVIGADO                46
CAUCASIA                28
SABANETA                27
TURBO                   25
COPACABANA              25
Name: count, dtype: int64

In [10]:
df4 = df3[(df3['departamentonombre']=='BOGOTA D.C.') | ((df3['departamentonombre']=='ANTIOQUIA') & ((df3['municipionombre']=='MEDELLIN') | (df3['municipionombre']=='ITAGUI') | (df3['municipionombre']=='BELLO') | (df3['municipionombre']=='SABANETA') | (df3['municipionombre']=='RIONEGRO') | (df3['municipionombre']=='ENVIGADO')))]
df4.reset_index(inplace = True)
df4.drop(columns = 'index',inplace = True)

C:\Users\pc\AppData\Local\Temp\ipykernel_21420\401858228.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop(columns = 'index',inplace = True)

In [54]:
df4.head(2)

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate
0,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00
1,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,TERPEL,CARRERA 27 No. 31C-63 SUR,BIODIESEL EXTRA,7986,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00

In [11]:
df4['departamentonombre'].unique()

array(['BOGOTA D.C.', 'ANTIOQUIA'], dtype=object)

In [32]:
df4['Dir2'] = df4['direccion'].apply(lambda x : x.replace('#','No'))
df4['Full_Address'] = df4.apply(lambda x : x['Dir2'] + ', ' + x['municipionombre'].capitalize() + ', Colombia' , axis = 1)

C:\Users\pc\AppData\Local\Temp\ipykernel_21420\1069916494.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Dir2'] = df4['direccion'].apply(lambda x : x.replace('#','No'))
C:\Users\pc\AppData\Local\Temp\ipykernel_21420\1069916494.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Full_Address'] = df4.apply(lambda x : x['Dir2'] + ', ' + x['municipionombre'].capitalize() + ', Colombia' , axis = 1)

In [33]:
df4['Full_Address'].nunique()

558

In [34]:
df4['Full_Address'][0]

'CALLE 45 No. 16-30, Bogota d.c., Colombia'

In [36]:
estaciones =  df4[['agente','Dir2','Full_Address']].drop_duplicates(subset = 'agente')
estaciones.reset_index(inplace = True)
estaciones.drop(columns = 'index',inplace = True)

In [37]:
estaciones['Full_Address'][0]

'CALLE 45 No. 16-30, Bogota d.c., Colombia'

In [38]:
address = estaciones['Full_Address'][0]
url = f'https://geocode.search.hereapi.com/v1/geocode?q={address}&apiKey={APIKEY_HERE_PLATFORM}'
response = requests.get(url).json()

In [39]:
response

{'items': [{'title': 'Avenida Calle 45 9-16, 110231 Bogotá, D.C., Colombia',
   'id': 'here:af:streetsection:CUj62WNnCkoYmZxg95FwnA:EAIaAjE2',
   'resultType': 'houseNumber',
   'houseNumberType': 'interpolated',
   'address': {'label': 'Avenida Calle 45 9-16, 110231 Bogotá, D.C., Colombia',
    'countryCode': 'COL',
    'countryName': 'Colombia',
    'countyCode': 'DC',
    'county': 'Bogotá, D.C.',
    'city': 'Bogotá, D.C.',
    'district': 'Chapinero',
    'street': 'Avenida Calle 45 9',
    'postalCode': '110231',
    'houseNumber': '16'},
   'position': {'lat': 4.63204, 'lng': -74.06546},
   'access': [{'lat': 4.63191, 'lng': -74.0655}],
   'mapView': {'west': -74.06636,
    'south': 4.63114,
    'east': -74.06456,
    'north': 4.63294},
   'scoring': {'queryScore': 0.9,
    'fieldScore': {'country': 1.0,
     'city': 1.0,
     'streets': [0.85],
     'houseNumber': 1.0}}},
  {'title': 'Calle 16-30, 110321 Bogotá, D.C., Colombia',
   'id': 'here:af:streetsection:bbKO2BHKtDta7HEFzbMp7A:EAIaAjMw',
   'resultType': 'houseNumber',
   'houseNumberType': 'interpolated',
   'address': {'label': 'Calle 16-30, 110321 Bogotá, D.C., Colombia',
    'countryCode': 'COL',
    'countryName': 'Colombia',
    'countyCode': 'DC',
    'county': 'Bogotá, D.C.',
    'city': 'Bogotá, D.C.',
    'district': 'Santa Fé',
    'street': 'Calle 16',
    'postalCode': '110321',
    'houseNumber': '30'},
   'position': {'lat': 4.60228, 'lng': -74.07204},
   'access': [{'lat': 4.60217, 'lng': -74.07211}],
   'mapView': {'west': -74.07294,
    'south': 4.60138,
    'east': -74.07114,
    'north': 4.60318},
   'scoring': {'queryScore': 0.69,
    'fieldScore': {'country': 1.0,
     'city': 1.0,
     'streets': [0.9],
     'houseNumber': 1.0}}}]}

In [40]:
def Get_Coords(address,apikey):
    
    url = f'https://geocode.search.hereapi.com/v1/geocode?q={address}&apiKey={apikey}'
    
    try : 
        
        response = requests.get(url).json()
        CleanAddress = response['items'][0]['title'].upper()
        LAT = response['items'][0]['position']['lat']
        LNG = response['items'][0]['position']['lng']
        
        results = [CleanAddress,LAT,LNG]
        
    except :
        
        results = ['Not Found','NA','NA']
        
    
    return results

In [41]:
Get_Coords(address,APIKEY_HERE_PLATFORM)

['AVENIDA CALLE 45 9-16, 110231 BOGOTÁ, D.C., COLOMBIA', 4.63204, -74.06546]

# Extracción de coordenadas

In [42]:
coordenadas = []
tiempo = [1,2,2.5]

for i in tqdm(range(len(estaciones['Full_Address'])),colour = 'green'):
    
    try :
        
        R = Get_Coords(estaciones['Full_Address'][i],APIKEY_HERE_PLATFORM)
        geo_source = R[1],R[2]
        coordenadas.append(geo_source)
        
    except :
        
        coordenadas.append('Error')
        
    
    time.sleep(random.choices(tiempo)[0])

100%|████████████████████████████████████████████████████████████████████████████████| 557/557 [27:01<00:00,  2.91s/it]

In [50]:
coordenadas

[(4.63204, -74.06546),
 (4.59549, -74.10256),
 (4.6322, -74.185),
 (4.60867, -74.20333),
 (4.75082, -74.04352),
 (4.65358, -74.13098),
 (6.25853, -75.58338),
 (4.70193, -74.02977),
 (4.74773, -74.04749),
 (4.5919, -74.08863),
 (4.74109, -74.0902),
 (4.68344, -74.09729),
 (6.27728, -75.58965),
 (6.22089, -75.5846),
 (4.57893, -74.12773),
 (4.63199, -74.10363),
 (4.69939, -74.11104),
 (6.2116, -75.57023),
 (4.57908, -74.09235),
 (4.6193, -74.12898),
 (4.65475, -74.14081),
 (4.60956, -74.1237),
 (4.68845, -74.09682),
 (4.70606, -74.09956),
 (4.67766, -74.07341),
 (4.70509, -74.0239),
 (4.69234, -74.04468),
 (6.26087, -75.58491),
 (6.15014, -75.62939),
 (6.23882, -75.59756),
 (4.59339, -74.09625),
 (4.53926, -74.13297),
 (4.63104, -74.07243),
 (4.66926, -74.15667),
 (6.28404, -75.55623),
 (4.77171, -74.0426),
 (4.67926, -74.15098),
 (4.54992, -74.08919),
 (4.70806, -74.09624),
 (4.75275, -74.0556),
 (4.68585, -74.15736),
 (4.65127, -74.1234),
 (4.571, -74.0992),
 (6.1668, -75.56927),
 (6.27146, -75.57393),
 (4.72411, -74.07244),
 (4.75838, -74.03972),
 (4.59442, -74.11187),
 (6.30102, -75.56425),
 (6.27361, -75.56485),
 (4.64681, -74.14591),
 (6.31399, -75.57681),
 (4.6802, -74.09978),
 (4.60204, -74.09358),
 (4.6915, -74.10843),
 (4.69297, -74.03081),
 (6.34741, -75.5202),
 (6.26337, -75.56995),
 (4.63944, -74.15715),
 (4.66929, -74.10961),
 (4.59513, -74.10083),
 (6.22652, -75.56506),
 (4.58958, -74.08027),
 (4.67393, -74.15156),
 (4.6542, -74.14142),
 (4.61544, -74.08129),
 (4.62154, -74.1249),
 (4.60444, -74.1244),
 (6.27001, -75.56549),
 (4.56505, -74.08909),
 (4.60739, -74.18354),
 (4.65451, -74.12231),
 (4.72652, -74.06109),
 (6.16033, -75.62452),
 (4.60199, -74.10177),
 (4.67612, -74.08398),
 (4.63486, -74.18029),
 (4.6176, -74.16426),
 (4.5253, -74.12661),
 (4.66236, -74.06636),
 (4.61601, -74.09353),
 (4.54859, -74.08876),
 (4.5839, -74.16865),
 (4.6887, -74.04718),
 (4.6695, -74.10964),
 (4.63932, -74.11648),
 (4.5984, -74.12836),
 (4.63761, -74.06338),
 (6.16889, -75.59824),
 (6.29358, -75.56128),
 (4.6944, -74.15145),
 (4.6233, -74.12847),
 (4.74967, -74.11563),
 (6.23212, -75.54063),
 (4.5533, -74.09912),
 (4.50686, -74.11173),
 (6.29305, -75.56188),
 (6.20753, -75.58557),
 (4.62965, -74.18332),
 (6.34552, -75.52319),
 (4.67689, -74.10215),
 (6.19855, -75.59342),
 (4.59211, -74.08844),
 (4.67713, -74.08593),
 (4.69486, -74.06834),
 (6.23447, -75.57449),
 (4.6678, -74.14191),
 (4.65058, -74.07265),
 (4.61616, -74.15995),
 (4.61872, -74.07497),
 (6.16382, -75.59605),
 (4.71967, -74.04667),
 (4.58172, -74.12751),
 (4.51851, -74.09091),
 (6.2647, -75.56743),
 (4.63064, -74.14392),
 (4.62404, -74.0759),
 (6.2873, -75.55524),
 (6.25048, -75.593),
 (4.73423, -74.0801),
 (4.68318, -74.09802),
 (4.70622, -74.05434),
 (4.53516, -74.11035),
 (4.68654, -74.08147),
 (6.23932, -75.58265),
 (4.62009, -74.1608),
 (4.53833, -74.13181),
 (4.64371, -74.07861),
 (6.21038, -75.58761),
 (4.64451, -74.11139),
 (4.61255, -74.13381),
 (6.23159, -75.5687),
 (6.25148, -75.60135),
 (6.2078, -75.58829),
 (4.66551, -74.0475),
 (4.62416, -74.07904),
 (4.5261, -74.11866),
 (4.62958, -74.07609),
 (4.71145, -74.14581),
 (4.67747, -74.11602),
 (4.65208, -74.11276),
 (4.66543, -74.04792),
 (4.69912, -74.11017),
 (6.17691, -75.58536),
 (4.81937, -74.03476),
 (4.60492, -74.14305),
 (4.59735, -74.07046),
 (4.66587, -74.07455),
 (4.58308, -74.16874),
 (4.63364, -74.10241),
 (6.20529, -75.58688),
 (6.24475, -75.60256),
 (6.17389, -75.58664),
 (4.65282, -74.05756),
 (6.24667, -75.55184),
 (4.63915, -74.15992),
 (4.5975, -74.12619),
 (6.26178, -75.54189),
 (4.70982, -74.05287),
 (4.78088, -74.08849),
 (6.20427, -75.58579),
 (4.59662, -74.17924),
 (4.60705, -74.08407),
 (4.58987, -74.0801),
 (6.24118, -75.57),
 (6.16079, -75.61744),
 (6.33836, -75.54661),
 (4.62499, -74.10176),
 (6.21733, -75.57077),
 (6.16871, -75.61848),
 (6.21134, -75.56673),
 (6.19245, -75.59384),
 (5.55841, -73.92726),
 (6.26647, -75.54611),
 (6.24605, -75.5926),
 (4.74655, -74.04676),
 (6.27572, -75.5729),
 (4.66999, -74.15586),
 (4.72914, -74.02428),
 (4.69146, -74.10845),
 (4.70217, -74.0495),
 (4.64499, -74.11025),
 (4.60899, -74.09637),
 (4.54635, -74.13739),
 (4.65906, -74.06947),
 (6.24874, -75.58298),
 (6.28621, -75.55853),
 (6.26724, -75.55787),
 (4.75939, -74.04474),
 (6.23687, -75.5757),
 (4.60987, -74.09568),
 (4.59545, -74.10234),
 (4.69811, -74.03135),
 (4.58084, -74.15452),
 (6.16358, -75.62275),
 (4.64151, -74.12302),
 (4.62816, -74.11051),
 (4.68228, -74.15538),
 (4.63841, -74.0697),
 (4.67014, -74.06406),
 (4.6571, -74.1379),
 (4.61391, -74.13604),
 (4.60463, -74.08132),
 (6.27674, -75.57058),
 (4.68125, -74.15357),
 (4.6538, -74.10332),
 (4.67559, -74.09248),
 (4.59251, -74.09112),
 (6.26067, -75.60554),
 (6.18095, -75.58207),
 (6.16273, -75.60259),
 (4.64116, -74.11417),
 (4.69216, -74.06673),
 (4.59174, -74.09811),
 (4.50891, -74.11593),
 (4.74738, -74.06466),
 (4.67577, -74.14038),
 (4.56516, -74.12458),
 (6.19118, -75.56109),
 (4.57948, -74.08622),
 (6.15397, -75.60944),
 (4.59222, -74.08863),
 (4.6169, -74.09453),
 (4.64593, -74.12418),
 (4.58125, -74.10275),
 (6.24489, -75.5892),
 (4.59445, -74.08421),
 (4.60701, -74.1678),
 (6.34575, -75.56505),
 (6.28742, -75.56972),
 (4.66158, -74.07353),
 (4.69373, -74.09124),
 (4.76387, -74.03242),
 (4.58874, -74.14104),
 (4.57922, -74.10722),
 (4.55316, -74.08969),
 (4.62831, -74.1117),
 (6.15544, -75.62414),
 (6.21548, -75.5877),
 (4.66231, -74.12654),
 (4.5981, -74.14489),
 (4.6873, -74.11021),
 (4.74313, -74.0927),
 (4.60623, -74.07673),
 (4.62997, -74.07854),
 (4.75777, -74.02778),
 (4.7334, -74.08748),
 (4.73107, -74.02415),
 (4.61545, -74.13999),
 (6.24361, -75.56038),
 (4.67648, -74.07558),
 (4.6874, -74.07428),
 (4.57939, -74.09941),
 (4.58205, -74.10055),
 (4.67607, -74.14087),
 (6.32746, -75.56008),
 (4.57782, -74.11175),
 (4.72325, -74.06677),
 (6.24539, -75.58697),
 (4.60096, -74.10404),
 (6.23023, -75.58286),
 (4.76245, -74.04919),
 (6.27309, -75.57312),
 (6.24385, -75.60059),
 (6.23497, -75.55598),
 (4.7676, -74.02824),
 (4.6844, -74.09736),
 (6.18661, -75.59833),
 (4.59386, -74.13004),
 (4.5764, -74.12857),
 (4.49289, -74.10307),
 (6.33171, -75.55857),
 (4.61305, -74.17148),
 (6.16783, -75.6073),
 (6.17741, -75.58382),
 (6.24928, -75.57796),
 (4.6687, -74.07959),
 (4.64169, -74.12379),
 (4.5894, -74.08039),
 (6.25055, -75.54839),
 (4.51279, -74.11346),
 (4.69258, -74.05724),
 (6.23643, -75.59299),
 (6.21317, -75.598),
 (6.25853, -75.58338),
 (4.74046, -74.02572),
 (4.60425, -74.09248),
 (4.65388, -74.05606),
 (6.16592, -75.57901),
 (4.7364, -74.08504),
 (4.59824, -74.10028),
 (6.18337, -75.65289),
 (4.76073, -74.03733),
 (4.59559, -74.12313),
 (4.61799, -74.14604),
 (6.26824, -75.56175),
 (4.70755, -74.07208),
 (6.2778, -75.55731),
 (4.59962, -74.0828),
 (4.61117, -74.14659),
 (4.74166, -74.11302),
 (4.61608, -74.16216),
 (4.71372, -74.0972),
 (6.1871, -75.57834),
 (4.61099, -74.0944),
 (4.68846, -74.06214),
 (4.65073, -74.07017),
 (4.70964, -74.05381),
 (6.2446, -75.59434),
 (4.59348, -74.08785),
 (4.58266, -74.06879),
 (4.66802, -74.09188),
 (6.22945, -75.60168),
 (4.60209, -74.13342),
 (6.33835, -75.54662),
 (4.62892, -74.08253),
 (4.62581, -74.12397),
 (6.33748, -75.54955),
 (4.61496, -74.06941),
 (4.71891, -74.09301),
 (6.25985, -75.5718),
 (4.58936, -74.16176),
 (4.60765, -74.10631),
 (6.2301, -75.56964),
 (4.74009, -74.08778),
 (4.70991, -74.13923),
 (6.16182, -75.6069),
 (4.56161, -74.12896),
 (6.15332, -75.61996),
 (4.70536, -74.10682),
 (4.66249, -74.06731),
 (4.69942, -74.07715),
 (4.73272, -74.09073),
 (6.33399, -75.55862),
 (4.63114, -74.11064),
 (4.68693, -74.12672),
 (4.71804, -74.06859),
 (6.29778, -75.56664),
 (6.17904, -75.60157),
 (4.62082, -74.18337),
 (6.20975, -75.58598),
 (4.59477, -74.14681),
 (4.50546, -74.09979),
 (4.61259, -74.14261),
 (6.32926, -75.55817),
 (4.54968, -74.08766),
 (4.5998, -74.08636),
 (4.64453, -74.11058),
 (4.68445, -74.05807),
 (4.70987, -74.05114),
 (6.16623, -75.54754),
 (4.60946, -74.18085),
 (4.62058, -74.09926),
 (4.61659, -74.09813),
 (4.61255, -74.07059),
 (4.6299, -74.16807),
 (6.27505, -75.6098),
 (6.16359, -75.62819),
 (6.20434, -75.50241),
 (4.74779, -74.0462),
 (6.30656, -75.54438),
 (4.68731, -74.04449),
 (4.59214, -74.09776),
 (6.29335, -75.59467),
 (4.62711, -74.11212),
 (4.56824, -74.15826),
 (4.58778, -74.179),
 (4.56116, -74.14545),
 (4.64499, -74.13096),
 (4.75561, -74.04491),
 (4.6429, -74.17106),
 (6.19221, -75.58),
 (6.27981, -75.63315),
 (6.2353, -75.54178),
 (4.73753, -74.10359),
 (4.7102, -74.04797),
 (4.59297, -74.09093),
 (4.6169, -74.13439),
 (4.68275, -74.0442),
 (4.59217, -74.08839),
 (6.34104, -75.5366),
 (4.71653, -74.05297),
 (4.69932, -74.04398),
 (4.58126, -74.15254),
 (4.55941, -74.1238),
 (6.17518, -75.59097),
 (6.29989, -75.55073),
 (6.25079, -75.60314),
 (6.29545, -75.56763),
 (4.62069, -74.18527),
 (6.26939, -75.57407),
 (4.65932, -74.05932),
 (4.76895, -74.02372),
 (4.60412, -74.06736),
 (6.22804, -75.57211),
 (4.73051, -74.02842),
 (4.60391, -74.12033),
 (6.32743, -75.54308),
 (4.67395, -74.10592),
 (4.69434, -74.12281),
 (6.2581, -75.58618),
 (4.57522, -74.15471),
 (6.2488, -75.56001),
 (4.58869, -74.115),
 (4.71627, -74.06041),
 (6.40563, -75.60017),
 (4.581, -74.08614),
 (6.17104, -75.62726),
 (4.61265, -74.07066),
 (6.20994, -75.56904),
 (6.17933, -75.57791),
 (4.59233, -74.08853),
 (6.16289, -75.5456),
 (6.18193, -75.61053),
 (6.26057, -75.56887),
 (6.27572, -75.5729),
 (6.23189, -75.59976),
 (4.62941, -74.19503),
 (4.58132, -74.09342),
 (6.18076, -75.59176),
 (4.68872, -74.16241),
 (4.69737, -74.10489),
 (6.29711, -75.54312),
 (6.23224, -75.59122),
 (4.65599, -74.05509),
 (6.28006, -75.56187),
 (4.57894, -74.08693),
 (6.17853, -75.63805),
 (4.60916, -74.06741),
 (6.17958, -75.59242),
 (4.74769, -74.05695),
 (4.67775, -74.14998),
 (4.66937, -74.15793),
 (6.1665, -75.61792),
 (6.14546, -75.62123),
 (4.65303, -74.11627),
 (4.59693, -74.11292),
 (4.54922, -74.137),
 (6.24716, -75.62251),
 (6.16239, -75.61453),
 (4.62183, -74.11015),
 (4.73265, -74.0563),
 (4.64171, -74.07206),
 (4.72372, -74.0629),
 (4.62693, -74.10797),
 (4.60435, -74.10094),
 (6.25802, -75.56781),
 (6.24183, -75.58214),
 (4.58965, -74.1497),
 (4.66606, -74.07489),
 (4.68385, -74.14214),
 (4.54668, -74.08707),
 ('NA', 'NA'),
 (4.67463, -74.06666),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA'),
 ('NA', 'NA')]

In [51]:
estaciones['Coords'] = coordenadas

In [57]:
estaciones

,agente,Dir2,Full_Address,Coords
0,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,CALLE 45 No. 16-30,"CALLE 45 No. 16-30, Bogota d.c., Colombia","(4.63204, -74.06546)"
1,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,CARRERA 27 No. 31C-63 SUR,"CARRERA 27 No. 31C-63 SUR, Bogota d.c., Colombia","(4.59549, -74.10256)"
2,EDS BIOMAX TINTAL,AVENIDA CALLE 54 SUR No 89A-55,"AVENIDA CALLE 54 SUR No 89A-55, Bogota d.c., C...","(4.6322, -74.185)"
3,ESTACION DE SERVICIO ESPERANZA BOSA,CARRERA 79 No. 74D-11,"CARRERA 79 No. 74D-11, Bogota d.c., Colombia","(4.60867, -74.20333)"
4,EDS LOS ABUELOS,CALLE 170 No. 20 A - 34,"CALLE 170 No. 20 A - 34, Bogota d.c., Colombia","(4.75082, -74.04352)"
...,...,...,...,...
552,ESTACION DE SERVICIO PETROBRAS IBERIA,AVENIDA CALLE 134 No. 53-51,"AVENIDA CALLE 134 No. 53-51, Bogota d.c., Colo...","(NA, NA)"
553,ESTACION BRIO IBERIA,CALLE 134A No. 53-85,"CALLE 134A No. 53-85, Bogota d.c., Colombia","(NA, NA)"
554,ESTACION DE SERVICIO TERPEL LA 45,CARRERA 45 No. 66-10,"CARRERA 45 No. 66-10, Medellin, Colombia","(NA, NA)"
555,EDS ESSO BOLIVARIANA,AVENIDA 33 No. 66A-21,"AVENIDA 33 No. 66A-21, Medellin, Colombia","(NA, NA)"
556,ESTACION TEXACO No 25,CALLE 11 SUR No. 15-11,"CALLE 11 SUR No. 15-11, Bogota d.c., Colombia","(NA, NA)"

In [24]:
len(df4)

1768

In [56]:
estaciones.head(2)

,agente,Dir2,Full_Address,Coords
0,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,CALLE 45 No. 16-30,"CALLE 45 No. 16-30, Bogota d.c., Colombia","(4.63204, -74.06546)"
1,ESTACION DE SERVICIO AUTOMOTRIZ SANTANDER,CARRERA 27 No. 31C-63 SUR,"CARRERA 27 No. 31C-63 SUR, Bogota d.c., Colombia","(4.59549, -74.10256)"

In [46]:
df_final = pd.merge(df4,estaciones[['Full_Address','Coords']],how = 'inner' , on = 'Full_Address')

In [29]:
df_final.head(3)

,departamentocodigo,departamentonombre,municipiocodigo,municipionombre,agente,bandera,direccion,producto,precio,estado,fecharegistro,FechaRegistroDate,Dir2,Full_Address,Coords
0,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,GASOLINA CORRIENTE OXIGENADA,9230,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00,CALLE 45 No. 16-30,"CALLE 45 No. 16-30, Bogota d.c., Colombia","(4.63204, -74.06546)"
1,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,BIODIESEL EXTRA,8440,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00,CALLE 45 No. 16-30,"CALLE 45 No. 16-30, Bogota d.c., Colombia","(4.63204, -74.06546)"
2,11,BOGOTA D.C.,11001,BOGOTA D.C.,ESTACION DE SERVICIO AUTOMOTRIZ PETROBRAS CALL...,PETROBRAS,CALLE 45 No. 16-30,BIOACEM AL 9%,8440,1,05/01/2018 12:00:00 AM,2018-05-01 12:00:00,CALLE 45 No. 16-30,"CALLE 45 No. 16-30, Bogota d.c., Colombia","(4.63204, -74.06546)"

In [47]:
df_final.to_csv('DATASET_FINAL.CSV',index = False)